version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  patient-service:
    build: .
    image: patient-service:latest
    container_name: patient-service
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy