name: Docker Build -> Push -> Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code (FIXED)
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    # 3. Build JAR
    - name: Build Jar
      run: mvn clean package -DskipTests

    # 4. Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5. Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/patient-service:latest .

    # 6. Push Image
    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/patient-service:latest

    # 7. Deploy to EC2
    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER  }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            # Stop old app container only (DON'T delete DB)
            docker stop patient-service || true
            docker rm patient-service || true
          
            # Create network
            docker network create my-network || true
          
            # Start Postgres (only if not exists)
            docker ps -a --format '{{.Names}}' | grep -q '^postgres$' || \
            docker run -d \
              --name postgres \
              --network my-network \
              -e POSTGRES_DB=patientdb \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=postgres \
              -v pgdata:/var/lib/postgresql/data \
              -p 5432:5432 \
              --restart always \
              postgres:15
          
            # Wait for DB
            sleep 10
          
            # Pull latest app image
            docker pull ${{ secrets.DOCKER_USERNAME }}/patient-service:latest
          
            # Start app
            docker run -d \
              --name patient-service \
              --network my-network \
              -p 4000:4000 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/patient-service:latest
